### PR TITLE
Consumer Search 

### PR DESCRIPTION
**Pull request by abhijeetgite**

### CODE REVIEW

**Comment by MubexOrg** [comment]
@jbejas i need you to review these two changes and determine if we can mege them

**Comment by jbejas** [comment]
@abhijeetgite we have several issues with pull request as described:

FUNCTIONS.PHP

1. Code indentation. We need to follow rules of indentation for proper readability. Remember that other team members, including myself, are going to review/update the code in the future, and we need to be able to read it.

2. Please add a comment with your name on every piece of code you add, so everybody can know who was working on it

3. PHP concatenation is incorrect. Here is an example.
Incorrect: $wpdb->get_var("show tables like '$partnerhip_consumer_tbl'")
Correct: $wpdb->get_var("show tables like " . $partnerhip_consumer_tbl)

Please update.

4. You need to work the code always in the same way. A lot of inconsistencies as described.
Incorrect: <a href ='.$url.'> (No space between variable concatenation)
Correct: <a href =' . $url . '> (Spacing between variable concatenation)

Incorrect: $email=$row->user_email;
Correct: $email = $row->user_email; (Note space between variable and value)
The same for comparison operators.

CUSTOM.JS

1. Correct usage of indentation, for proper readability.
2. Remove all Javascript. Make full usage of jQuery.
3. Review spacing on variable -> value declaration.

4. URL declaration incorrect.
node.setAttribute("href", "http://127.0.0.1/wordpress/"+res[i].link);
Use PHP on functions.php to add base_url on footer and include the variable con custom.js
This declaration creates a problem in any future URL migration.

5. Do not add inline styles on any element. Add Class or ID and link using "Custom CSS & JS" Plugin adding a new entry with a representative title that anybody can understand.

6. Line 76. Remove alert showing user that is not logged in. We need to discuss with Chris, the proper way to show the user this message.

7. Add comments on all pieces of code you add or work on, so we can know who made every change.

**Comment by abhijeetgite** [comment]
Hello Sebastian,

   Thanks for reviewing code. I have made all changes mentioned by you, and will follow the same in future. It's always been good practice to follow coding standard. I have checked in the code in MINDNERVES branch . Also will use different branch name as per standards.

Only thing i have not change is "show tables like '$campaign_tbl' " as i have also tried the same method mentioned by you but it was lead to error , I will check and clean that in upcoming build.

Thanks,

Abhijeet Gite

**Comment by MubexOrg** [comment]
@abhijeetgite will make a new request

**Pull request closed without merging**
